galaxy_info:
  role_name: etcd
  author: rasta-rocket
  description: Etcd role
  company: OpenInfraCorp
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags: []

dependencies: []
