- name: "service : upload systemd unit file"
  template:
    src: "{{ consul.service.src }}"
    dest: "{{ consul.service.dest }}"
    mode: "{{ consul.service.mode }}"
  notify:
    - "reload systemd"
    - "restart consul"
