- name: "user : create consul user"
  user:
    name: "{{ consul.user.name }}"
    group: "{{ consul.user.group }}"
    groups: "{{ consul.user.groups }}"
    uid: "{{ consul.user.uid }}"
    shell: "/usr/sbin/nologin"
