galaxy_info:
  role_name: docker
  author: rasta-rocket
  description: Docker role
  company: OpenInfraCorp
  license: Apache 2.0
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags: []

dependencies: []
