netbox:
  install:
    git:
      netbox:
        repo: https://github.com/digitalocean/netbox.git
        dest: /opt/netbox
        version: master
    apt:
      - python3 
      - python3-dev
      - python3-setuptools
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - graphviz
      - libpq-dev
      - libssl-dev
      - zlib1g-dev
      - python3-pip
      - python3-virtualenv
    pip:
      netbox:
        requirements: /opt/netbox/requirements.txt
  configure: []
