- name: "Install VPN"
  include_tasks: install.yml

- name: "Upload files"
  include_tasks: upload.yml

- name: "Configure VPN"
  include_tasks: configure.yml

- name: "Set network configuration"
  include_tasks: network.yml
