- name: "Configure : create/update etcd configuration file"
  template:
    src: "{{ etcd.configure.template.src }}"
    dest: "{{ etcd.configure.directory }}/{{ etcd.configure.template.dest }}"
    mode: "{{ etcd.configure.template.mode }}"
    owner: "{{ etcd.user.name }}"
    group: "{{ etcd.group.name }}"
  notify: "restart etcd"
