- name: "Install : Include role.install_from_archive"
  include_role:
    name: base
    tasks_from: install_from_archive
  vars:
    archive: "{{ item }}"
    binary_path: "{{ item.path }}"
  with_items: "{{ etcd.install.from_archive }}"
