- name: "Service : upload systemd unit file"
  template:
    src: "{{ etcd.service.template.src }}"
    dest: "{{ etcd.service.template.dest }}"
    mode: "{{ etcd.service.template.mode }}"
  notify:
    - "reload systemd"
    - "restart etcd"
