- name: "main : reload systemd configuration"
  systemd:
    daemon_reload: yes
  listen: "reload systemd"

- name: "main : restart etcd"
  systemd:
    name: etcd
    state: restarted
  listen: "restart etcd"
